//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public string Id { get; set; }
        public string FollowerUserId { get; set; }
        public string FollowingUserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User AspNetUser { get; set; }
        public virtual User AspNetUser1 { get; set; }
    }
}
